// <auto-generated />
namespace projectMotosel.Migrations.ExcelMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class changed_stuff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_stuff));
        
        string IMigrationMetadata.Id
        {
            get { return "201505070513101_changed_stuff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
