// <auto-generated />
namespace projectMotosel.Migrations.ExcelMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Removed_Required_in_DeliveryListCustomerId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removed_Required_in_DeliveryListCustomerId));
        
        string IMigrationMetadata.Id
        {
            get { return "201505062308143_Removed_[Required]_in_DeliveryList.CustomerId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
