// <auto-generated />
namespace projectMotosel.Migrations.ExcelMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Sale_constructor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sale_constructor));
        
        string IMigrationMetadata.Id
        {
            get { return "201505071807000_Sale_constructor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
